auto_tune:
  action: DIRECT_IP
  convergence_tolerance: 0.01
  emergency_stop: 90.0
  enabled: true
  input_span: 100.0
  max_duration_sec: 120
  output_span: 200.0
  output_start: 0.0
  output_step: 30.0
  samples: 600
  settle_time_sec: 10
  test_time_sec: 60
  tuning_method: MIXED_PID
logging:
  database_path: pid_data.db
  interval_sec: 1.0
pid:
  action: DIRECT
  p_mode: P_ON_ERROR
  d_mode: D_ON_ERROR
  i_aw_mode: I_AW_OFF
  kd: 0.0
  ki: 0.0
  kp: 0.0
  output_limits:
    max: 100.0
    min: -100.0
  sample_time_us: 100000
